spring.application.name=parseforge

spring.datasource.url=jdbc:postgresql://localhost:5432/parseforge
spring.datasource.username=parseforge
spring.datasource.password=parseforge

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata

spring.jpa.open-in-view=false

spring.flyway.enabled=true

server.port=8080

management.endpoints.web.exposure.include=health,info

minio.endpoint=http://localhost:9000
minio.access-key=parseforge
minio.secret-key=parseforge123
minio.bucket=parseforge-documents