spring.application.name=parseforge

spring.datasource.url=jdbc:postgresql://localhost:5432/parseforge
spring.datasource.username=parseforge
spring.datasource.password=parseforge

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata